**shape manipulation**

In [ ]:
import numpy as np

a = np.array([[1,2,3,4] , [5,4,3,6] , [3,6,4,3]])
print(a)

[[1 2 3 4]
 [5 4 3 6]
 [3 6 4 3]]


In [ ]:
#12 => (1,12), (12,1) , (2,6) , (6,2) , (3,4) , (4,3)

b = a.reshape(4,3)
print(b)

[[1 2 3]
 [4 5 4]
 [3 6 3]
 [6 4 3]]


In [ ]:
c = np.arange(0,16)
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [ ]:
d = c.reshape(4,4)
print(d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
print(d.ndim)
print(d.shape)

2
(4, 4)


In [ ]:
print(d.ravel())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [ ]:
print(d.flatten())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


**Indexing and slicing**

In [ ]:
arr1 = np.array([[4,5,3,2,1] , [6,3,8,9,2] , [3,6,5,4,9]])
print(arr1)

[[4 5 3 2 1]
 [6 3 8 9 2]
 [3 6 5 4 9]]


In [ ]:
#access an element from first row (index 0) and second column (index 1)

print(arr1[0,1])
print(arr1[1,2])

5
8


In [ ]:
#slicing -> subsetting a numpy array

print(arr1[1 : 3 , 2 : 5])

[[8 9 2]
 [5 4 9]]


In [ ]:
print(arr1[0:3 , 2 : 2+2])

[[3 2]
 [8 9]
 [5 4]]


In [ ]:
#last columns
print(arr1[: , 4:])

[[1]
 [2]
 [9]]


In [ ]:
print(arr1[: , -1:])

[[1]
 [2]
 [9]]


In [ ]:
#last row
print(arr1[2: , :])

[[3 6 5 4 9]]


In [ ]:
print(arr1[:2 , :])

[[4 5 3 2 1]
 [6 3 8 9 2]]


In [ ]:
print(arr1[: , 3:])

[[2 1]
 [9 2]
 [4 9]]


In [ ]:
print(arr1[: , :3])

[[4 5 3]
 [6 3 8]
 [3 6 5]]


**Numpy - Array Joining & Splitting**

In [1]:
import numpy as np

a = np.array([[2,4,5] , [6,4,3]])
print(a)

print()

b = np.array([[1,5,3] , [7,5,4]])
print(b)

[[2 4 5]
 [6 4 3]]

[[1 5 3]
 [7 5 4]]


In [2]:
c = np.concatenate((a,b))
print(c)

[[2 4 5]
 [6 4 3]
 [1 5 3]
 [7 5 4]]


In [4]:
d = np.concatenate((a,b) , axis = 1)
print(d)

[[2 4 5 1 5 3]
 [6 4 3 7 5 4]]


In [5]:
e = np.hstack((a,b))
print(e)

[[2 4 5 1 5 3]
 [6 4 3 7 5 4]]


In [6]:
f = np.vstack((a,b))
print(f)

[[2 4 5]
 [6 4 3]
 [1 5 3]
 [7 5 4]]


In [8]:
n1 = np.array([1,2,3,4,5,6])
g = np.split(n1,3)
print(g)
print(g[0])
print(g[1])

[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]
[3 4]


In [9]:
n1 = np.array([[1,2],[3,4],[5,6]])
print(n1)

print()

g = np.split(n1,3)
print(g)
print(g[0])
print(g[1])

[[1 2]
 [3 4]
 [5 6]]

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]
[[1 2]]
[[3 4]]
