**shape manipulation**

In [1]:
import numpy as np

a = np.array([[1,2,3,4] , [5,4,3,6] , [3,6,4,3]])
print(a)

[[1 2 3 4]
 [5 4 3 6]
 [3 6 4 3]]


In [3]:
#12 => (1,12), (12,1) , (2,6) , (6,2) , (3,4) , (4,3)

b = a.reshape(4,3)
print(b)

[[1 2 3]
 [4 5 4]
 [3 6 3]
 [6 4 3]]


In [4]:
c = np.arange(0,16)
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [5]:
d = c.reshape(4,4)
print(d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [7]:
print(d.ndim)
print(d.shape)

2
(4, 4)


In [8]:
print(d.ravel())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [9]:
print(d.flatten())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
