In [1]:
a = 7
print(a * 2)

14


In [2]:
b = [4,3,2,1,9]
print(b * 2)

[4, 3, 2, 1, 9, 4, 3, 2, 1, 9]


In [12]:
c = [3,'a',2.1]
print(c)

[3, 'a', 2.1]


In [3]:
import numpy as np

arr1 = np.array([4,3,2,1,9])
print(arr1)

[4 3 2 1 9]


In [4]:
print(arr1 * 3)

[12  9  6  3 27]


In [7]:
print(arr1.ndim)
print(arr1.shape)
print(arr1.size)

1
(5,)
5


In [8]:
arr2 = np.array([[3,4,5] , [4,3,2]])
print(arr2)

[[3 4 5]
 [4 3 2]]


In [11]:
print(arr2.ndim)
print(arr2.shape)
print(arr2.size)

2
(2, 3)
6


In [13]:
arr3 = np.array([3,'a',2.1])
print(arr3)

['3' 'a' '2.1']


In [14]:
arr4 = np.array([[[3,4,5] , [4,3,2]] , [[13,14,15] , [14,13,12]]])
print(arr4)

[[[ 3  4  5]
  [ 4  3  2]]

 [[13 14 15]
  [14 13 12]]]


In [17]:
print(arr4.ndim)
print(arr4.shape)
print(arr4.size)

3
(2, 2, 3)
12
