**shape manipulation**

In [ ]:
import numpy as np

a = np.array([[1,2,3,4] , [5,4,3,6] , [3,6,4,3]])
print(a)

[[1 2 3 4]
 [5 4 3 6]
 [3 6 4 3]]


In [ ]:
#12 => (1,12), (12,1) , (2,6) , (6,2) , (3,4) , (4,3)

b = a.reshape(4,3)
print(b)

[[1 2 3]
 [4 5 4]
 [3 6 3]
 [6 4 3]]


In [ ]:
c = np.arange(0,16)
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [ ]:
d = c.reshape(4,4)
print(d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
print(d.ndim)
print(d.shape)

2
(4, 4)


In [ ]:
print(d.ravel())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [ ]:
print(d.flatten())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


**Indexing and slicing**

In [ ]:
arr1 = np.array([[4,5,3,2,1] , [6,3,8,9,2] , [3,6,5,4,9]])
print(arr1)

[[4 5 3 2 1]
 [6 3 8 9 2]
 [3 6 5 4 9]]


In [ ]:
#access an element from first row (index 0) and second column (index 1)

print(arr1[0,1])
print(arr1[1,2])

5
8


In [ ]:
#slicing -> subsetting a numpy array

print(arr1[1 : 3 , 2 : 5])

[[8 9 2]
 [5 4 9]]


In [ ]:
print(arr1[0:3 , 2 : 2+2])

[[3 2]
 [8 9]
 [5 4]]


In [ ]:
#last columns
print(arr1[: , 4:])

[[1]
 [2]
 [9]]


In [ ]:
print(arr1[: , -1:])

[[1]
 [2]
 [9]]


In [ ]:
#last row
print(arr1[2: , :])

[[3 6 5 4 9]]


In [ ]:
print(arr1[:2 , :])

[[4 5 3 2 1]
 [6 3 8 9 2]]


In [ ]:
print(arr1[: , 3:])

[[2 1]
 [9 2]
 [4 9]]


In [ ]:
print(arr1[: , :3])

[[4 5 3]
 [6 3 8]
 [3 6 5]]


**Numpy - Array Joining & Splitting**

In [ ]:
import numpy as np

a = np.array([[2,4,5] , [6,4,3]])
print(a)

print()

b = np.array([[1,5,3] , [7,5,4]])
print(b)

[[2 4 5]
 [6 4 3]]

[[1 5 3]
 [7 5 4]]


In [ ]:
c = np.concatenate((a,b))
print(c)

[[2 4 5]
 [6 4 3]
 [1 5 3]
 [7 5 4]]


In [ ]:
d = np.concatenate((a,b) , axis = 1)
print(d)

[[2 4 5 1 5 3]
 [6 4 3 7 5 4]]


In [ ]:
e = np.hstack((a,b))
print(e)

[[2 4 5 1 5 3]
 [6 4 3 7 5 4]]


In [ ]:
f = np.vstack((a,b))
print(f)

[[2 4 5]
 [6 4 3]
 [1 5 3]
 [7 5 4]]


In [ ]:
n1 = np.array([1,2,3,4,5,6])
g = np.split(n1,3)
print(g)
print(g[0])
print(g[1])

[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]
[3 4]


In [ ]:
n1 = np.array([[1,2],[3,4],[5,6]])
print(n1)

print()

g = np.split(n1,3)
print(g)
print(g[0])
print(g[1])

[[1 2]
 [3 4]
 [5 6]]

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]
[[1 2]]
[[3 4]]


**Array Broadcasting**
  * Broadcasting allows us to perform arhthemetic operations on arrays of different shapes
  * This mechanism stretches the smaller array to match the shape of the larger array without making an actual copy of the data, thus enabling efficient computation.
  Rules of Broadcasting

  * Broadcasting follows specific rules to determine if two arrays are compatible:

    * Compare shapes: Starting with the trailing dimensions (i.e., the rightmost), compare dimensions one by one.
    * Compatible dimensions: Dimensions are compatible if:
        * They are equal, or
        * One of them is 1.

If the shapes are not compatible, broadcasting will raise an error.

In [3]:
import numpy as np

n1 = np.array([1,2,3,4])
print(n1)

print()

x = 2
print(n1 * 2)

[1 2 3 4]

[2 4 6 8]


In [4]:
n2 = np.array([3,4,5,6])
y = np.array([2,1,3,1])

print(n2 * y)

[ 6  4 15  6]


In [9]:
n3 = np.array([[3,4,5,6] , [2,1,8,7]])
y = np.array([[2,1,3,1]])

print(n3)
print("Shape of n3" , n3.shape)
print()
print(y)
print("shape of y", y.shape)

[[3 4 5 6]
 [2 1 8 7]]
Shape of n3 (2, 4)

[[2 1 3 1]]
shape of y (1, 4)


In [10]:
print(n3 * y)

[[ 6  4 15  6]
 [ 4  1 24  7]]


In [11]:
n4 = np.array([[3,4,5,6] , [2,1,8,7]])
y = np.array([[2,1],[3,1]])

print(n3)
print("Shape of n3" , n3.shape)
print()
print(y)
print("shape of y", y.shape)

[[3 4 5 6]
 [2 1 8 7]]
Shape of n3 (2, 4)

[[2 1]
 [3 1]]
shape of y (2, 2)


In [12]:
print(n3 * y)

ValueError: operands could not be broadcast together with shapes (2,4) (2,2) 

In [13]:
n4 = np.array([[3,4,5,6] , [2,1,8,7]])
y = np.array([[2],[3]])

print(n3)
print("Shape of n3" , n3.shape)
print()
print(y)
print("shape of y", y.shape)

[[3 4 5 6]
 [2 1 8 7]]
Shape of n3 (2, 4)

[[2]
 [3]]
shape of y (2, 1)


In [14]:
print(n3 * y)

[[ 6  8 10 12]
 [ 6  3 24 21]]
